# Generated by Django 3.1 on 2020-08-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quota', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, choices=[('mb', 'MB'), ('gb', 'GB'), ('tb', 'TB')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DateTimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=True)),
            ],
            options={
                'verbose_name': 'Date',
                'verbose_name_plural': 'Dates',
            },
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(default='', verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(default='Self', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DataTransferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_bytes', models.BigIntegerField(default=100, verbose_name='bytes')),
                ('size', models.FloatField(default=100, verbose_name='Transferred')),
                ('size_type', models.CharField(blank=True, choices=[('b', 'B'), ('kb', 'kB'), ('mb', 'MB'), ('gb', 'GB'), ('tb', 'TB')], default=('b', 'B'), max_length=50, null=True, verbose_name='size')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resourcemodel')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datetimemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
            options={
                'verbose_name': 'Data transfer',
                'verbose_name_plural': 'Data transfer',
                'ordering': ['-id'],
            },
        ),
    ]
